services:
  vintage-story:
    image: ghcr.io/${IMAGE_NAME:-vintage-story-server}:${GITHUB_REF_NAME:-dev}
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      cache_from:
        - "type=gha"
      cache_to:
        - "type=gha"
