services:
  vintage-story:
    image: ghcr.io/${IMAGE_NAME:-vintage-story-server}:${GITHUB_REF_NAME:-dev}${PUSH_LATEST:+,ghcr.io/${IMAGE_NAME:-vintage-story-server}:latest}
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - "type=gha"
      cache_to:
        - "type=gha"

      x-bake:
        platforms:
          - "linux/amd64"
          - "linux/arm64"
