services:
  vintage-story-server:
    image: vintage-story-server:dev

    environment:
      VERSION: "1.20.3"
    volumes:
      - "./data:/data"
    ports: ["42420:42420"]
    stdin_open: true
    tty: true
